### ISSUE TITLE
[H/W PART] Make a connection

### ISSUE THREAD

**Issue by othellowhite** [MyHappyHog/ProjectPrototype#2]
Make a connection between Arduino and Laptop

**Comment by kiriung** [comment]
connection error happend because xbee shield is not good at wireless connection
some question -> write dh with 8bit number or 6bit number (ex. 0013A200 or 13A200)
why we can't do xbee to xbee wireless connection?
is it because kind of shield?

**Comment by othellowhite** [comment]
1. Make sure Destination Address High(DH) be 8-bit, Not just 6-bit
   - We are not sure mask bit will be in front of address
2. XBee-USB connector is so weird
   - Report to research note that Xbee connection works fine on Arduino 
3. And i don't know why issue tracker can't set dual assignee
